### ISSUE TITLE
Guidelines for workshop leader(s)

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/spotlight-workshop#1]
To do: 
- [ ] Introduction to the classroom/FAC/house rules/seating arrangement
- [ ] Encourage/demand pairing 
- [ ] Structure/schedule for the evening (90 minutes session) 
- [ ] Assess student level (ice breaker name game?)
- [ ] Doodle poll to schedule mentors / assign roles - Zooey/Yvonne at all sessions
- [ ] Feedback forms / stop-go-continue with mentors after each session 
- [ ] Get DBS numbers from mentors / email Spotlight coordinator 
- [x] Figure out curriculum (loose)
- [ ] Aim to have a project theme for students 
- [ ] Hand-over notes for FAC11 - document everything!
- [ ] Resource list / run-through resource list

**Comment by ZooeyMiller** [comment]
We've figured out a loose curriculum as seen in the README.md, using Dan's guidelines from his old workshops. 

We're in the process of getting the DBS numbers from FAC10 and any others who got hteir DBS through STEMnet.

We have sent out a doodle poll, and almost all of FAC10 have now filled it out (waiting for 2 responses).

The Eventbrite page is also made and sorted.

We are working on sorting the other bits and pieces during today's biz dv time and definitely before Monday 27th (the first session! eek!).
