### ISSUE TITLE
Eventbrite page for promotion 

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/spotlight-workshop#2]
We need an Eventbrite page for our three workshops.

**Comment by yvonne-liu** [comment]
Link [here](https://www.eventbrite.co.uk/e/coding-club-with-founders-coders-tickets-32759879682?utm_source=eb_email&utm_medium=email&utm_campaign=order_confirmation_email&utm_term=eventname&ref=eemailordconf)

**Comment by ZooeyMiller** [comment]
This has been sorted, see the link in Yvonne's latest comment. :fire:
